log-path     = "/home/john/temp/logs/gf-home"
keywords    = "Go,MVC,HTTPServer,TCPServer,UDPServer,WebServer,Cookie,Session,ORM,golang,cache,goframe, go frame,gf"
description = "模块化、松耦合、轻量级、高性能的Go语言Web开发框架。支持热重启、热更新、多域名、多端口、多服务、HTTP/HTTPS、动态路由等特性，并提供了Web服务开发的系列核心组件，如：Router、Cookie、Session、服务注册、配置管理、模板引擎、数据校验、分页管理、数据库ORM等等等等，并且提供了数十个实用开发模块集，如：缓存、日志、时间、命令行、二进制、文件锁、对象池、连接池、数据编码、进程管理、进程通信、TCP/UDP组件、并发安全容器、Goroutine池等等等等等等。"
http-port   = 80
https-port  = 443

# https设置
[ssl]
    key = "/home/john/Workspace/Go/gf-home/config/ssl/ssl.key"
    crt = "/home/john/Workspace/Go/gf-home/config/ssl/ssl.crt"

# 官网首页设置
[index]
    title = "官方网站 - GoFrame开发框架"

# 开发文档设置
[doc]
    title = "GoFrame框架开发文档 - Powered by GoFrame"
    path  = "/home/john/Workspace/Go/gf-doc2"
    hook  = "pass"
    [doc.admin]
        user = "admin"
        pass = "123"

# CDN配置
[cdn]
    url     = "https://cdn.gfer.me"
    version = "v=1"